# Time-stamp: <2017-08-09 23:54:50 vk>
# -*- coding: utf-8 -*-

* What the heck is this for?

The author is supervising several student works. Since each of them is
finalizing their work more or less in parallel, there is a need for a
structured way of supervision.

No student should suffer from being forgotten nor should get feedback
too late. Being a supervisor is not the biggest part of my job and so
I need a *common* procedure. I simply can not remember/maintain the
preferred data flow mechanism of each and every student. So students
have to adopt to my method.

And this is document describes the method.

PS: Do not hesitate and contact me if you have suggestions!

* Process Components

The supervision process consists of multiple parts:
- Following the Rules: how to keep students up to date on the process here
- Communication Channels and Setup: how to exchange files and information
- Individual Appointments: regular meetings with the students
- Regular Submissions of PDF files: how to supervise content
- Weekly LaTeX-Q&A: there are always things you can learn about LaTeX
- LaTeX Code: basic rules and direct feedback

** Following the Rules

This process is hosted [[https://github.com/novoid/Student-Supervision-Process][as a github project]].

You can «follow» the project on github and regularly monitor its
changes which is recommended but not mandatory. General
[[https://www.changedetection.com/][notifier-services]] are being blocked by github and can not be used for
following the [[https://github.com/novoid/Student-Supervision-Process/commits/master/][changes here]].

Changes will be announced via email to all of my students.

** Communication Channels and Setup

*** Asynchronous Communication

My *preferred* way of communicating with you is via *email*. I am
fairly good reachable per email, even on evenings and most weekends.

*** Synchronous Communication

If you want to get in touch with me for instant feedback, call my
*office phone number*. Either I am in my office and can answer your
call or (after four? times of ringing) you will be routed to my
cellphone. If you land in my voice mail system, I am currently
speaking to someone else or my phone is off (during sleeping hours).

You might as well ask me for my *[[http://en.wikipedia.org/wiki/Jabber][Jabber]] ID*.

Sorry, I do have strong arguments against usage of Skype. But you
might as well ask me for my Google+ ID and schedule a *Google hangout*
there.

*** Submitting PDF files

I am using a tablet computer to read your PDF submission. This way I
read and annotate the *content* of your thesis.

Please use [[https://syncthing.net/][Syncthing]] instead of cloud-based services like Dropbox. It
maintains our level of privacy without exposing data to the public
cloud.

Syncthing is available for all major operating systems except Apple
iOS because Apple is prohibiting tools like Syncthing as they
prohibited tools like external keyboards for many years.

Create a Syncthing folder for your thesis using any name you wish. I
rename it to «LASTNAME_THESISTYPE» on my side (only) anyway.
(«Thesistype» is either «Bakk» or «DA».)

After you have created your Synthing folder, please do send me your
device ID ([[http://127.0.0.1:8384/][web interface]] > Actions > Show ID) and the ID of your
shared folder (expand the folder in the web interface).

*** Submitting LaTeX source code

You are going to set up a [[http://en.wikipedia.org/wiki/Git][Git]] repository especially for your LaTeX
document. Even if you already have a Git repository for source code or
such, please do create another one solely for your thesis document as
well.

Please contact me for getting information where to push your local Git
changes to.

Do *not* wait for some final chapter or so to check in! *Check in
often!* Use it as an off-site backup in case your computer fails or in
case you delete large portions of text by mistake. Never think that
this will not be the case. We are all humans so we all make mistakes.
Even me :-)

** Individual Appointments

Each student gets a weekly 30 minute slot or a bi-weekly 60 minute
slot. If you think I need to do a small internet research by myself
for a question you have got, email me your question(s) upfront.

Agenda:
- What happened since the last appointment?
- What were the problems?
- Probably: comments about the last PDF submission
- Probably: comments about the LaTeX source
- Next steps and deliverables until next appointment

If the appointment should be canceled, write me an email at least one
day in advance. Short term cancels only via synchronous communication
channels such as phone.

** Regular Submissions of PDF Files

This is about the *content* of your thesis.

If you finish a certain part of your document:
1. Generate the PDF file
2. Put it in the shared Syncthing folder
3. Rename it to =YYYY-MM-DD_TYPE_LASTNAME_-_optional_things.PDF=
4. Send me an email, describing the parts I should check

File name convention examples:
- minimal example: =2012-03-18_DA_Smith.pdf=
- example with comment: =2012-03-19_Bakk_Mueller_-_chap_2-4_ready_for_persual.pdf=

After I checked the content of your document, you will may annotations
in the PDF file which will be discussed at the next individual
appointment.

I might as well add comments in your LaTeX code as well.

** Weekly LaTeX Questions and Answers

We will schedule a weekly hour for LaTeX-specific questions and best
practices. It is *not mandatory* but highly recommended. Especially at
an early stage of your thesis!

I assume that you already have [[http://LaTeX.TUGraz.at][basic LaTeX knowledge]]. At this
LaTeX-Q&A I will show examples of LaTeX source code and suggest things
that spare you lots of time (and nerves).

Please be assured: although I stick to current LaTeX code issues of my
students, this event is *not* intended to offend the work of single
persons! It demonstrates optimizations and encourages learning for
everybody.

I will keep individual LaTeX code optimizations to a minimum and
explain things *only* at this LaTeX-Q&A meetings! You will see: your
colleagues make the same mistakes as you do. And as I have done a
couple of years ago.

Occasionally, this LaTeX meetings may be canceled. In this case, I
will send an email preferably at least two days in advance.

** LaTeX Code

This is about the *form* of your thesis.

You *have* to use the LaTeX typesetting system to write your
thesis. For millions of reasons there is no arguing for doing it in
other systems. Sorry for that.

I will keep individual LaTeX code optimizations to a minimum and
explain LaTeX-related things *only* at the LaTeX-Q&A meetings!

I assume that you already have [[http://LaTeX.TUGraz.at][basic LaTeX knowledge]].

- Use the LaTeX [[http://latex.tugraz.at/vorlagen/allgemein#laengeres_dokument_wie_diplomarbeit_dissertation_buch][thesis template of LaTeX@TUG]]
  - you can use your own thesis template as long as you know what you
    are doing (I will check!)
  - especially as LaTeX beginner: *never* write your own template or
    preamble. Trust me. [[http://www.urbandictionary.com/define.php?term%3Dbtdt][BTDT]] :-)
- In any case: please read the content of the example chapters of [[http://latex.tugraz.at/vorlagen/allgemein#laengeres_dokument_wie_diplomarbeit_dissertation_buch][the
  LaTeX@TUG template]]!
- Use the [[http://www.ctan.org/tex-archive/macros/latex/contrib/todonotes/][todonotes]] packet
  - add the «listoftodos» command in your document to get an overview
    of open issues
  - Annotations and suggestions will be done using todonotes snippets
    within your tex-files
  - use todonotes by annotating open issues by yourself
- Check in all necessary files for compilation into the Git repository
  - do not forget images and such
  - do use *meaningful submit messages* in the commit line
- Maintain a script that generates the PDF file completely
  - the thesis template of LaTeX@TUG offers a [[http://en.wikipedia.org/wiki/Makefile][makefile]] for that
    purpose
- Make sure your LaTeX-editor ...
  - uses a decent *spell checker*
  - produces UTF-8 compatible TeX-files
  - does not produce line lengths longer than the usual 70-90
    characters in your TeX-files
- Do not check in the PDF output files into the Git repository
  of your thesis unless we agree on an exception
  - you can [[https://git-scm.com/docs/gitignore][ignore files for Git]] and thus keep them only for your own

There is an even longer [[https://github.com/dspinellis/latex-advice][page with excellent tips on how to write LaTeX
documents]]. I recommend you to read it as well. Some details do differ
from your situation here because you are using a different LaTeX
template (KOMA script) where following things are handled differently:
- no natbib
- no doublespace (it's not even maintained any more)
- no geometry
- no pslatex

* License

[[https://github.com/novoid/Student-Supervision-Process][Student Supervision Process]] by Karl Voit is licensed under a
[[http://creativecommons.org/licenses/by-nc-sa/3.0/][Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License]]
